services:
  web_server:
    image: nginx_server
    build: /webServer
    ports:
      - "80:80"
    networks:
      - spaAuthNetwork
    volumes:
      - ./webServer/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webServer/nginx/conf.d:/etc/nginx/conf.d
      - ./webServer/nginx/logs:/var/log/nginx
      - ./webServer/nginx/data:/usr/share/nginx/data
    env_file: "/webServer/webServer.env"
    restart: always
  my_sql:
    image: mysql_database
    build: /mySQL
    ports:
      - "3306:3306"
    networks:
      - spaAuthNetwork
    volumes:
      - ./mySQL/data:/var/lib/mysql
    env_file: "/mySQL/mySQL.env"
    restart: always
  backend:
    tty: true
    image: backend_java
    build: /Java
    command: /app/projects/spaAuth/mvnw clean spring-boot:run
    ports:
      - "8888:8080"
    networks:
      - spaAuthNetwork
    # volumes:
    #   - ./Java/spaAuth:/app/projects/spaAuth
    develop:
      watch:
        # - action: rebuild
        #   path: ./Java/spaAuth/pom.xml
        #   target: /app/projects/spaAuth/pom.xml
        - action: sync+restart
          path: ./Java/spaAuth
          target: /app/projects/spaAuth
    env_file: "/Java/spaAuth.env"
    depends_on:
      - my_sql
      - web_server
  vite_react:
    tty: true
    image: vite_react
    build: /ViteReact
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8000:8000"
    networks:
      - spaAuthNetwork
    volumes:
      - ./ViteReact/ViteReact:/app/ViteReact
    env_file: "/ViteReact/viteReact.env"
    depends_on:
      - my_sql
      - web_server

networks:
  spaAuthNetwork:
    name: spaAuthNetwork
    driver: bridge
