# Use the official MySQL image as a base
FROM mysql:latest

# Set the default user for the MySQL image
USER mysql

# Expose port 3306 to allow connections to the database
EXPOSE 3306

# Start the MySQL server when the container is run
CMD ["mysqld"]